@extends('frontend.cartography.layout')

@section('cartography_section')
	Histórico
@stop

@section('cartography_content')
	<p>&nbsp;Ap&oacute;s sua formaliza&ccedil;&atilde;o, a Comiss&atilde;o de Cartografia Geot&eacute;cnica e Geoambiental da ABGE come&ccedil;ou elaborar um levantamento de dados e cadastro de institui&ccedil;&otilde;es, profissionais e trabalhos relacionado &agrave; Cartografia Geot&eacute;cnica e Geoambiental do Brasil. Para o registro dos dados, foram elaboradas planilhas cadastrais para institui&ccedil;&otilde;es, profissionais e para os trabalhos desenvolvidos. Os dados foram tabulados e uma an&aacute;lise preliminar foi feita obtendo-se um panorama da produ&ccedil;&atilde;o brasileira em cartografia geot&eacute;cnica e geoambiental. Estes resultados foram apresentados no 5&ordm; Simp&oacute;sio Brasileiro de Cartografia Geot&eacute;cnica e Geoambiental, realizado em 2004, <st1:personname productid="em S?o Carlos" w:st="on">em S&atilde;o Carlos</st1:personname> (SP). Ap&oacute;s o evento, o N&uacute;cleo Minas Gerais da ABGE assumiu a montagem e organiza&ccedil;&atilde;o de um banco de dados a partir do cadastro existente. Os resultados preliminares desta etapa foram discutidos durante o XI Congresso Brasileiro de Geologia de Engenharia e Ambiental, realizado em Florian&oacute;polis no ano de 2005. O Banco de Dados sobre a Cartografia Geot&eacute;cnica e Geoambiental do Brasil ser&aacute; uma base de dados de toda produ&ccedil;&atilde;o brasileira em cartografia geot&eacute;cnica e geoambiental desenvolvida em universidades, institutos de pesquisa, &oacute;rg&atilde;os p&uacute;blicos e pelo setor privado no Brasil.</p>
	<p class="MsoNormal"><span lang="PT-BR">Est&atilde;o lan&ccedil;ados no banco todos os trabalhos publicados nos Simp&oacute;sios Brasileiros, Congressos Brasileiros de Geololgia de Engenharia, Revista Solos e Rochas, Revista Geotecnia e alguns de outros eventos. Faltam ainda trabalhos de p&oacute;s-gradua&ccedil;&atilde;o, inicia&ccedil;&atilde;o cient&iacute;fica, relat&oacute;rios t&eacute;cnicos e trabalhos publicados em outros eventos e peri&oacute;dicos que n&atilde;o puderam ser levantados at&eacute; o momento. O Banco de Dados ter&aacute; a alimenta&ccedil;&atilde;o feita pelos pr&oacute;prios autores, que dever&atilde;o se cadastrar no mesmo e lan&ccedil;ar seus trabalhos. O procedimento para esta tarefa constar&atilde;o no pr&oacute;prio Banco de Dados e seguir&aacute; as normas bibliogr&aacute;ficas da ABNT, com outras informa&ccedil;&otilde;es tais como Institui&ccedil;&atilde;o, local do trabalho, escala e resumo. Assim, solicitamos o empenho de todos no lan&ccedil;amento das informa&ccedil;&otilde;es de forma a termos um banco de dados o mais completo poss&iacute;vel, assim como a divulga&ccedil;&atilde;o do mesmo, inclusive a outras entidades t&eacute;cnico-cient&iacute;ficas.&nbsp;<o:p></o:p></span></p> 
@stop